name: my_environment  # replace 'my_environment' with your desired environment name

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - pip

  # PyTorch and related packages
  - pytorch=1.8.0
  - torchvision=0.9.0

  # Other required packages
  - numpy=1.24.0
  - opencv-python=4.1.2
  - pyyaml=5.3.1
  - scipy=1.4.1
  - tqdm=4.41.0
  - addict=2.4.0
  - tensorboard=2.7.0
  - pycocotools=2.0
  - onnx=1.10.0
  - onnx-simplifier=0.3.6
  - thop
